name: Run Tests

on:
  push:
    branches: [main, Dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 23
      - run: cd Server && npm install && npm run test
